### ISSUE TITLE
Not able to see anything 

### ISSUE THREAD

**Issue by Shailesh1709** [Hujjat/laravel-crud#2]
![image](https://user-images.githubusercontent.com/43522933/46261219-ffb37d80-c50d-11e8-9765-15b5a2139d1e.png)
After running this file  i am not able to see home page
while going to http://localhost:8000/home 
It automatically redirects to http://localhost:8000/login .

Please help !

**Comment by Hujjat** [comment]
You Don't have access to /home unless you are logged in. Register a new user and then you will be okay :)
