### ISSUE TITLE
Screen Category did not apper

### ISSUE THREAD

**Issue by ghost** [Hujjat/laravel-crud#3]
At left side, apper Posts and not apper Category, why ?
![ft](https://user-images.githubusercontent.com/6104968/46418010-3ef5f000-c701-11e8-856d-8eaa60435c2d.jpg)

**Comment by Hujjat** [comment]
this repo is based on the video tutorial here
https://www.youtube.com/watch?v=hiaYGxA8IWQ&index=1&list=PLB4AdipoHpxYmPdyI3e-yH58-3CS4qoAf

It doesn't have any post feature. I just teach how to create CRUD with Laravel.
